networks:
  default:
    external: true
    name: shared

services:
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    shm_size: 1g
    # ports:
    # - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=$PG_PASS
      - POSTGRES_DB=theprime
  redis:
    image: redis:bookworm
    restart: unless-stopped
    # ports:
    # - 6379:6379
    volumes:
      - ./redis:/data
    command: [ "redis-server", "--appendonly", "yes", "--appendfilename", "appendonly.aof", "--dir", "/data" ]
  nats:
    image: nats:2.10.26
    # ports:
    # - "4222:4222"
    # - "8222:8222"
    volumes:
      - ./nats:/data
    command: [ "-js", "-m", "8222", "-sd", "/data" ]

  api:
    image: api
    restart: unless-stopped
    environment:
      - CONFIG=${API_CONFIG}
  webhook:
    image: webhook
    restart: unless-stopped
    environment:
      - CONFIG=${WEBHOOK_CONFIG}
  worker:
    image: worker
    restart: unless-stopped
    environment:
      - CONFIG=${WORKER_CONFIG}
  support:
    image: support
    restart: unless-stopped
    environment:
      - CONFIG=${SUPPORT_CONFIG}
